language: node_js
node_js:
  - 14

before_install: 
  - npm install -g serverless
before_script:
  - npm test

stages:
  - stage
  - prod

jobs:
  include:
    - stage: stage
      if: branch = "stage"
      script:
        - npm run deploy:dev
    - stage: prod
      if: branch = "master"
      script:
        - npm run deploy:prod