language: node_js
node_js:
  - 14

before_install: 
  - npm install -g serverless

stages:
  - test
  - dryrun
  - stage
  - prod

jobs:
  include:
    - stage: test # runs default script, which is npm test
    - stage: dryrun 
      if: branch NOT IN (master, stage)
      script: serverless deploy --noDeploy
    - stage: stage
      if: branch = "stage"
      script:
        - npm run deploy:dev
    - stage: prod
      if: branch = "master"
      script:
        - npm run deploy:prod